# Generated by Django 3.2.15 on 2022-12-04 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_alter_user_access_token'),
        ('horus', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vname', models.CharField(max_length=255, null=True)),
                ('video_url', models.CharField(max_length=255, null=True)),
                ('owner', models.ForeignKey(db_column='owner', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'videos',
            },
        ),
    ]
