# Generated by Django 3.2.15 on 2022-12-05 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('horus', '0003_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='npz_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='VInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_info_id', models.CharField(max_length=255, null=True)),
                ('video', models.ForeignKey(db_column='video', null=True, on_delete=django.db.models.deletion.CASCADE, to='horus.video')),
            ],
            options={
                'db_table': 'vinfo',
            },
        ),
    ]
