# Generated by Django 3.2.15 on 2022-12-05 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horus', '0004_auto_20221205_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='complete',
            field=models.SmallIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
